---
name: Merges

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # Value of the distributionManagement/repository/id field of
          # the pom.xml
          server-id: release
          # Location for the settings.xml file
          settings-path: ${{ github.workspace }}/.m2/

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/.m2/settings.xml
        env:
          MAVEN_RELEASE_REPO_USER: ${{ github.USER }}
          MAVEN_RELEASE_REPO_PASS: ${{ github.token }}
