---
name: Releases

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
      MAVEN_OPTS: "-Dmaven.repo.local=$HOME/.m2/repository"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Strip SNAPSHOT Version
        run: |
          mvn $MAVEN_CLI_OPTS \
            versions:set versions:update-child-modules versions:commit \
            -DremoveSnapshot \
            -DgenerateBackupPoms=false
      - name: Publish GitHub Packages
        run: |
          mvn $MAVEN_CLI_OPTS \
            deploy \
            -D altDeploymentRepository=release::default::${MAVEN_RELEASE_REPO_URL}
        env:
          MAVEN_RELEASE_REPO_USER: ${{ github.actor }}
          MAVEN_RELEASE_REPO_PASS: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_RELEASE_REPO_URL: https://maven.pkg.github.com/${{ github.repository }}
